<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

ModuleNotFoundError: No module named 'matplotlib'

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [8]:
#ваш код здесь

data = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")
print(data.shape)

(44744, 12)

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [25]:
#ваш код здесь

import pandas as pd

df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Вывод нескольких первых строк
print(df.head())

# Вывод нескольких последних строк
print(df.tail())

                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто
0  Имеется собственный автомобиль
1                      Не указано
2                      Не указано
3                      Не указано
4                      Не указано
                                       Пол, возраст           ЗП  \
44739    Мужчина ,  30 лет , родился 17 января 1989   50000 руб.
44740      Мужчина ,  27 лет , родился 5 марта 1992   39000 руб.
44741  Женщина ,  48 лет , родилась 26 декабря 1970   40000 руб.
44742   Мужчина ,  24 года , родился 6 октября 1994   20000 руб.
44743    Мужчина ,  38 лет , родился 25 апреля 1980  120000 руб.

                               Ищет работу на должность:  \
44739  Финансист, аналитик, экономист, бухгалтер, мен...
44740             Системный администратор, IT-специалист
44741                         Аналитик данных, Математик
44742                                   Контент-менеджер
44743                               Руководитель проекта

                            Город, переезд, командировки  \
44739  Тверь , готов к переезду (Москва, Химки) , гот...
44740  Липецк , готов к переезду , готов к командировкам
44741  Челябинск , готова к переезду , готова к редки...
44742  Тамбов , не готов к переезду , не готов к кома...
44743  Москва , не готов к переезду , не готов к кома...

                                               Занятость  \
44739                                   полная занятость
44740  проектная работа, частичная занятость, полная ...
44741                                   полная занятость
44742              частичная занятость, полная занятость
44743                                   полная занятость

                                                  График  \
44739                      полный день, удаленная работа
44740  удаленная работа, гибкий график, полный день, ...
44741                      полный день, удаленная работа
44742                                   удаленная работа
44743                                        полный день

                                             Опыт работы  \
44739  Опыт работы 7 лет 7 месяцев  Финансист, аналит...
44740  Опыт работы 7 лет  Системный администратор, IT...
44741  Опыт работы 21 год 5 месяцев  Январь 1998 — по...
44742  Опыт работы 3 года 10 месяцев  Контент-менедже...
44743  Опыт работы 15 лет 10 месяцев  Руководитель пр...

                         Последнее/нынешнее место работы  \
44739  ООО "IAS" (независимый участник объединения Ru...
44740                                       ИП Пестрецов
44741  ОАО «ЧМК», Исследовательско-Технологический Це...
44742                                          IQ-Maxima
44743                                  ПАО ГК ТНС энерго

                    Последняя/нынешняя должность  \
44739                     Руководитель субгруппы
44740                            Предприниматель
44741                 Начальник группы аналитики
44742                          Менеджер проектов
44743  Руководитель отдела технической поддержки

                                       Образование и ВУЗ Обновление резюме  \
44739  Высшее образование 2015  Московский гуманитарн...  22.04.2019 12:32
44740  Высшее образование (Бакалавр) 2016  Воронежски...  22.04.2019 13:11
44741  Высшее образование 2000  Южно-Уральский госуда...  09.04.2019 05:07
44742  Высшее образование 2015  Тамбовский государств...  26.04.2019 14:25
44743  Высшее образование 1997  Южно-Российский госуд...  05.07.2018 20:15

                                 Авто
44739                      Не указано
44740                      Не указано
44741                      Не указано
44742  Имеется собственный автомобиль
44743                      Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

4. Обратите внимание на информацию о числе непустых значений.

In [11]:
#ваш код здесь

# Загрузка данных в DataFrame
dataframe = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Получение количества непустых значений в каждом столбце
non_empty_counts = dataframe.notnull().sum()

# Вывод информации о количестве непустых значений и типе данных каждого столбца
for col, count in non_empty_counts.items():
    print(f"Column: {col}, Non-Empty Values: {count}, Type: {dataframe[col].dtype}")

Column: Пол, возраст, Non-Empty Values: 44744, Type: object
Column: ЗП, Non-Empty Values: 44744, Type: object
Column: Ищет работу на должность:, Non-Empty Values: 44744, Type: object
Column: Город, переезд, командировки, Non-Empty Values: 44744, Type: object
Column: Занятость, Non-Empty Values: 44744, Type: object
Column: График, Non-Empty Values: 44744, Type: object
Column: Опыт работы, Non-Empty Values: 44576, Type: object
Column: Последнее/нынешнее место работы, Non-Empty Values: 44743, Type: object
Column: Последняя/нынешняя должность, Non-Empty Values: 44742, Type: object
Column: Образование и ВУЗ, Non-Empty Values: 44744, Type: object
Column: Обновление резюме, Non-Empty Values: 44744, Type: object
Column: Авто, Non-Empty Values: 44744, Type: object

5. Выведите основную статистическую информацию о столбцах.

Образование: высшее, неоконченное высшее, среднее специальное, среднее полное, основное общее, начальное общее. 

Авто: легковой автомобиль, грузовой автомобиль, автобус, мотоцикл, мопед, трамвай, троллейбус, трактор, самоходная машина, гужевой транспорт. 

Должность: руководитель организации, заместитель руководителя, главный бухгалтер, начальник отдела, специалист, стажёр, технический работник, уборщик служебных помещений, дворник, курьер. 

Место работы: организация, индивидуальный предприниматель, акционерное общество, общество с ограниченной ответственностью, потребительский кооператив, товарищество собственников недвижимости, публично-правовая компания, государственная корпорация, муниципальное учреждение, орган государственной власти, орган местного самоуправления, адвокатский кабинет, нотариальная контора, религиозная организация. 

Город: Москва, Санкт-Петербург, Новосибирск, Екатеринбург, Нижний Новгород, Казань, Челябинск, Омск, Самара, Ростов-на-Дону, Уфа, Красноярск, Пермь, Воронеж, Волгоград, Краснодар, Саратов, Тюмень, Тольятти, Ижевск, Барнаул, Иркутск, Ульяновск, Хабаровск, Ярославль, Владивосток, Махачкала, Томск, Оренбург, Кемерово, Новокузнецк, Рязань, Астрахань, Набережные Челны, Пенза, Липецк, Киров, Чебоксары, Тула, Калининград, Балашиха, Курск, Ставрополь, Улан-Удэ, Севастополь, Тверь, Магнитогорск, Брянск, Иваново, Сочи, Белгород, Нижний Тагил, Владимир, Чита, Грозный, Симферополь, Калуга, Волжский, Саранск, Череповец, Вологда, Якутск, Подольск, Мурманск, Сургут, Орёл, Великий Новгород, Дзержинск, Братск, Петрозаводск, Новороссийск, Старый Оскол, Нижневартовск, Архангельск, Сыктывкар, Бийск, Псков, Энгельс, Рыбинск, Прокопьевск, Южно-Сахалинск, Ноябрьск, Златоуст, Кострома, Химки, Йошкар-Ола, Люберцы, Северодвинск, Новочеркасск, Мытищи, Кирово-Чепецк, Батайск, Шахты, Новошахтинск, Волгодонск, Абакан, Щёлково, Электросталь, Альметьевск, Салават, Пятигорск, Рубцовск, Копейск, Первоуральск, Майкоп, Новомосковск, Хасавюрт, Назрань, Керчь, Каменск-Уральский, Нефтекамск, Отрадный, Невинномысск, Димитровград, Обнинск, Новый Уренгой, Находка, Армавир, Железногорск, Ногинск, Серпухов, Октябрьский, Новотроицк, Одинцово, Елец, Домодедово, Березники, Северск, Старый Оскол, Коломна, Сергиев Посад, Новомосковск, Жуковский, Дербент, Камышин, Пролетарск, Кызыл, Октябрьский, Зугдиди, Черкесск, Щучин, Кисловодск, Шарыпово, Ачинск, Артем, Зеленодольск, Красногорск, Соликамск, Междуреченск, Сарапул, Канск, Белорецк, Великие Луки, Всеволожск, Алексин, Верхняя Пышма, Великий Устюг, Берёзовский, Гатчина, Сосновый Бор, Отрадное, Краснотурьинск, Балахна, Лесосибирск, Фокино, Кимры, Печоры, Краснокамск, Сокол, Сухой Лог, Чайковский, Новоуральск, Югорск, Лысьва, Губкинский, Уварово, Комсомольск-на-Амуре, Раменское, Муравленко, Углич, Чернушка, Сертолово

In [12]:
#ваш код здесь

def main():

    df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")
    
    # Вывод основной статистической информации о столбцах
    print("Образование:\n", df['образование'].unique(), "\n")
    print("Автомобиль:\n", df['авто'].unique(), "\n")
    print("Должность:\n", df['должность'].unique(), "\n")
    print("Место работы:\n", df['место_работы'].unique(), "\n")
    print("Город:\n", df['город'].unique(), "\n")

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [13]:
#ваш код здесь

#Для выполнения данной задачи юзаем функцию `pandas.Series.map()`. Эта функция позволяет нам создать новое значение для каждой 
# строки в серии на основе сопоставления существующего значения с ключом.

#создадим словарь, который будет использоваться для сопоставления различных уровней образования:


education_mapping = {
    "Высшее образование": "высшее",
    "Неоконченное высшее образование": "неоконченное высшее",
    "Среднее специальное образование": "среднее специальное",
    "Среднее полное образование": "среднее"
}


#Теперь мы можем применить этот словарь к столбцу `Образование и ВУЗ` с помощью `map()`:


# Предположим, что у нас есть DataFrame под названием 'df' с колонкой 'Образование и ВУЗ'
# df['Образование и ВУЗ'] = [...]  # Заполнение колонки данными

# Создаем новый столбец 'Образование' с использованием map
df['Образование'] = df['Образование и ВУЗ'].map(education_mapping)

# Проверяем категории с помощью unique()
print(df['Образование'].unique())


#Этот код создаст новый столбец `Образование`, где каждому уровню образования будет присвоена соответствующая категория.
# Метод `unique()` покажет нам уникальные значения в новом столбце, что позволит нам проверить правильность категоризации.
#После создания нового столбца `Образование`, мы можем удалить столбец `Образование и ВУЗ`:

del df['Образование и ВУЗ']

#Теперь у нас есть новый столбец `Образование` с четырьмя категориями, соответствующими уровням образования, 
# и удаленный столбец `Образование и ВУЗ`.

[nan]

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина.
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '.
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [27]:


df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")


# Функция для извлечения пола и возраста
def extract_gender_age(text):
    gender_map = {'Мужчина': 'М', 'Женщина': 'Ж'}
    parts = text.split(' , ')
    gender = gender_map.get(parts[0], 'Неизвестно')
    age = int(parts[1].split()[0])
    return gender, age

# Применение функции и создание новых столбцов
df[['Пол', 'Возраст']] = df['Пол, возраст'].apply(lambda x: pd.Series(extract_gender_age(x)))

# Удаление старого столбца
df = df.drop(columns=['Пол, возраст'])

# Вывод первых строк для проверки
print("Первые строки:")
print(df.head())

# Вывод последних строк для проверки
print("\nПоследние строки:")
print(df.tail())

Первые строки:
            ЗП                          Ищет работу на должность:  \
0   29000 руб.                            Системный администратор
1   40000 руб.                               Технический писатель
2   20000 руб.                                           Оператор
3  100000 руб.  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4  140000 руб.                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто Пол  Возраст
0  Имеется собственный автомобиль   М       39
1                      Не указано   М       60
2                      Не указано   Ж       36
3                      Не указано   М       38
4                      Не указано   Ж       26

Последние строки:
                ЗП                          Ищет работу на должность:  \
44739   50000 руб.  Финансист, аналитик, экономист, бухгалтер, мен...
44740   39000 руб.             Системный администратор, IT-специалист
44741   40000 руб.                         Аналитик данных, Математик
44742   20000 руб.                                   Контент-менеджер
44743  120000 руб.                               Руководитель проекта

                            Город, переезд, командировки  \
44739  Тверь , готов к переезду (Москва, Химки) , гот...
44740  Липецк , готов к переезду , готов к командировкам
44741  Челябинск , готова к переезду , готова к редки...
44742  Тамбов , не готов к переезду , не готов к кома...
44743  Москва , не готов к переезду , не готов к кома...

                                               Занятость  \
44739                                   полная занятость
44740  проектная работа, частичная занятость, полная ...
44741                                   полная занятость
44742              частичная занятость, полная занятость
44743                                   полная занятость

                                                  График  \
44739                      полный день, удаленная работа
44740  удаленная работа, гибкий график, полный день, ...
44741                      полный день, удаленная работа
44742                                   удаленная работа
44743                                        полный день

                                             Опыт работы  \
44739  Опыт работы 7 лет 7 месяцев  Финансист, аналит...
44740  Опыт работы 7 лет  Системный администратор, IT...
44741  Опыт работы 21 год 5 месяцев  Январь 1998 — по...
44742  Опыт работы 3 года 10 месяцев  Контент-менедже...
44743  Опыт работы 15 лет 10 месяцев  Руководитель пр...

                         Последнее/нынешнее место работы  \
44739  ООО "IAS" (независимый участник объединения Ru...
44740                                       ИП Пестрецов
44741  ОАО «ЧМК», Исследовательско-Технологический Це...
44742                                          IQ-Maxima
44743                                  ПАО ГК ТНС энерго

                    Последняя/нынешняя должность  \
44739                     Руководитель субгруппы
44740                            Предприниматель
44741                 Начальник группы аналитики
44742                          Менеджер проектов
44743  Руководитель отдела технической поддержки

                                       Образование и ВУЗ Обновление резюме  \
44739  Высшее образование 2015  Московский гуманитарн...  22.04.2019 12:32
44740  Высшее образование (Бакалавр) 2016  Воронежски...  22.04.2019 13:11
44741  Высшее образование 2000  Южно-Уральский госуда...  09.04.2019 05:07
44742  Высшее образование 2015  Тамбовский государств...  26.04.2019 14:25
44743  Высшее образование 1997  Южно-Российский госуд...  05.07.2018 20:15

                                 Авто Пол  Возраст
44739                      Не указано   М       30
44740                      Не указано   М       27
44741                      Не указано   Ж       48
44742  Имеется собственный автомобиль   М       24
44743                      Не указано   М       38

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**.

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [28]:
#ваш код здесь

import pandas as pd
import numpy as np


# Чтение CSV файла
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Функция для извлечения опыта работы в месяцах
def extract_experience_months(text):
    if pd.isna(text) or text == "Не указано":
        return np.nan
    
    text = text.split(' ', 3)[2]  # Извлекаем часть с опытом работы
    years = months = 0

    if 'год' in text:
        years = int(text.split('год')[0].strip())
        text = text.split('год', 1)[1].strip()

    if 'месяц' in text:
        months = int(text.split('месяц')[0].strip())
    
    return years * 12 + months

# Применение функции и создание нового столбца
df['Опыт работы (месяц)'] = df['Опыт работы'].apply(extract_experience_months)

# Удаление старого столбца
df = df.drop(columns=['Опыт работы'])

# Вывод первых строк для проверки
print("Первые строки:")
print(df.head())

# Вывод последних строк для проверки
print("\nПоследние строки:")
print(df.tail())

Первые строки:
                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто  Опыт работы (месяц)
0  Имеется собственный автомобиль                  0.0
1                      Не указано                  0.0
2                      Не указано                  0.0
3                      Не указано                  0.0
4                      Не указано                  0.0

Последние строки:
                                       Пол, возраст           ЗП  \
44739    Мужчина ,  30 лет , родился 17 января 1989   50000 руб.
44740      Мужчина ,  27 лет , родился 5 марта 1992   39000 руб.
44741  Женщина ,  48 лет , родилась 26 декабря 1970   40000 руб.
44742   Мужчина ,  24 года , родился 6 октября 1994   20000 руб.
44743    Мужчина ,  38 лет , родился 25 апреля 1980  120000 руб.

                               Ищет работу на должность:  \
44739  Финансист, аналитик, экономист, бухгалтер, мен...
44740             Системный администратор, IT-специалист
44741                         Аналитик данных, Математик
44742                                   Контент-менеджер
44743                               Руководитель проекта

                            Город, переезд, командировки  \
44739  Тверь , готов к переезду (Москва, Химки) , гот...
44740  Липецк , готов к переезду , готов к командировкам
44741  Челябинск , готова к переезду , готова к редки...
44742  Тамбов , не готов к переезду , не готов к кома...
44743  Москва , не готов к переезду , не готов к кома...

                                               Занятость  \
44739                                   полная занятость
44740  проектная работа, частичная занятость, полная ...
44741                                   полная занятость
44742              частичная занятость, полная занятость
44743                                   полная занятость

                                                  График  \
44739                      полный день, удаленная работа
44740  удаленная работа, гибкий график, полный день, ...
44741                      полный день, удаленная работа
44742                                   удаленная работа
44743                                        полный день

                         Последнее/нынешнее место работы  \
44739  ООО "IAS" (независимый участник объединения Ru...
44740                                       ИП Пестрецов
44741  ОАО «ЧМК», Исследовательско-Технологический Це...
44742                                          IQ-Maxima
44743                                  ПАО ГК ТНС энерго

                    Последняя/нынешняя должность  \
44739                     Руководитель субгруппы
44740                            Предприниматель
44741                 Начальник группы аналитики
44742                          Менеджер проектов
44743  Руководитель отдела технической поддержки

                                       Образование и ВУЗ Обновление резюме  \
44739  Высшее образование 2015  Московский гуманитарн...  22.04.2019 12:32
44740  Высшее образование (Бакалавр) 2016  Воронежски...  22.04.2019 13:11
44741  Высшее образование 2000  Южно-Уральский госуда...  09.04.2019 05:07
44742  Высшее образование 2015  Тамбовский государств...  26.04.2019 14:25
44743  Высшее образование 1997  Южно-Российский госуд...  05.07.2018 20:15

                                 Авто  Опыт работы (месяц)
44739                      Не указано                  0.0
44740                      Не указано                  0.0
44741                      Не указано                  0.0
44742  Имеется собственный автомобиль                  0.0
44743                      Не указано                  0.0

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , …
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [30]:
#ваш код здесь

# Чтение CSV файла
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Список городов-миллионников
million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск',
                  'Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь',
                  'Воронеж','Волгоград']

# Функция для извлечения данных из столбца "Город, переезд, командировки"
def extract_city_relocation_travel(text):
    parts = text.split(' , ')
    city = parts[0].strip()
    relocation = any(keyword in text for keyword in ['готов к переезду', 'хочу переехать'])
    travel = 'готов к командировкам' in text

    if city in ['Москва', 'Санкт-Петербург']:
        city_category = city
    elif city in million_cities:
        city_category = 'город-миллионник'
    else:
        city_category = 'другие'
    
    return city_category, relocation, travel

# Применение функции и создание новых столбцов
df[['Город', 'Готовность к переезду', 'Готовность к командировкам']] = df['Город, переезд, командировки'].apply(lambda x: pd.Series(extract_city_relocation_travel(x)))

# Замена пропусков в "Готовность к командировкам" на False
df['Готовность к командировкам'].fillna(False, inplace=True)

# Удаление старого столбца
df = df.drop(columns=['Город, переезд, командировки'])

# Вывод первых строк для проверки
print("Первые строки:")
print(df.head())

# Вывод последних строк для проверки
print("\nПоследние строки:")
print(df.tail())

Первые строки:
                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто   Город  Готовность к переезду  \
0  Имеется собственный автомобиль  другие                   True
1                      Не указано  другие                   True
2                      Не указано  другие                  False
3                      Не указано  другие                   True
4                      Не указано  Москва                  False

   Готовность к командировкам
0                        True
1                       False
2                       False
3                       False
4                       False

Последние строки:
                                       Пол, возраст           ЗП  \
44739    Мужчина ,  30 лет , родился 17 января 1989   50000 руб.
44740      Мужчина ,  27 лет , родился 5 марта 1992   39000 руб.
44741  Женщина ,  48 лет , родилась 26 декабря 1970   40000 руб.
44742   Мужчина ,  24 года , родился 6 октября 1994   20000 руб.
44743    Мужчина ,  38 лет , родился 25 апреля 1980  120000 руб.

                               Ищет работу на должность:  \
44739  Финансист, аналитик, экономист, бухгалтер, мен...
44740             Системный администратор, IT-специалист
44741                         Аналитик данных, Математик
44742                                   Контент-менеджер
44743                               Руководитель проекта

                                               Занятость  \
44739                                   полная занятость
44740  проектная работа, частичная занятость, полная ...
44741                                   полная занятость
44742              частичная занятость, полная занятость
44743                                   полная занятость

                                                  График  \
44739                      полный день, удаленная работа
44740  удаленная работа, гибкий график, полный день, ...
44741                      полный день, удаленная работа
44742                                   удаленная работа
44743                                        полный день

                                             Опыт работы  \
44739  Опыт работы 7 лет 7 месяцев  Финансист, аналит...
44740  Опыт работы 7 лет  Системный администратор, IT...
44741  Опыт работы 21 год 5 месяцев  Январь 1998 — по...
44742  Опыт работы 3 года 10 месяцев  Контент-менедже...
44743  Опыт работы 15 лет 10 месяцев  Руководитель пр...

                         Последнее/нынешнее место работы  \
44739  ООО "IAS" (независимый участник объединения Ru...
44740                                       ИП Пестрецов
44741  ОАО «ЧМК», Исследовательско-Технологический Це...
44742                                          IQ-Maxima
44743                                  ПАО ГК ТНС энерго

                    Последняя/нынешняя должность  \
44739                     Руководитель субгруппы
44740                            Предприниматель
44741                 Начальник группы аналитики
44742                          Менеджер проектов
44743  Руководитель отдела технической поддержки

                                       Образование и ВУЗ Обновление резюме  \
44739  Высшее образование 2015  Московский гуманитарн...  22.04.2019 12:32
44740  Высшее образование (Бакалавр) 2016  Воронежски...  22.04.2019 13:11
44741  Высшее образование 2000  Южно-Уральский госуда...  09.04.2019 05:07
44742  Высшее образование 2015  Тамбовский государств...  26.04.2019 14:25
44743  Высшее образование 1997  Южно-Российский госуд...  05.07.2018 20:15

                                 Авто             Город  \
44739                      Не указано            другие
44740                      Не указано            другие
44741                      Не указано  город-миллионник
44742  Имеется собственный автомобиль            другие
44743                      Не указано            Москва

       Готовность к переезду  Готовность к командировкам
44739                   True                        True
44740                   True                        True
44741                  False                       False
44742                   True                        True
44743                   True                        True

C:\Users\user\AppData\Local\Temp\ipykernel_12944\409094181.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Готовность к командировкам'].fillna(False, inplace=True)

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [31]:
#ваш код здесь

import pandas as pd

# Чтение CSV файла
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Преобразование "Занятость"
employment_types = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']
for employment in employment_types:
    df[employment] = df['Занятость'].apply(lambda x: employment in x)

# Преобразование "График"
schedule_types = ['полный день', 'сменный график', 'гибкий график', 'удаленная работа', 'вахтовый метод']
for schedule in schedule_types:
    df[schedule] = df['График'].apply(lambda x: schedule in x)

# Удаление исходных столбцов
df = df.drop(columns=['Занятость', 'График'])

# Вывод первых строк для проверки
print("Первые строки:")
print(df.head())

# Вывод последних строк для проверки
print("\nПоследние строки:")
print(df.tail())

Первые строки:
                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто  полная занятость  частичная занятость  \
0  Имеется собственный автомобиль              True                 True
1                      Не указано              True                 True
2                      Не указано              True                False
3                      Не указано              True                 True
4                      Не указано              True                False

   проектная работа  волонтерство  стажировка  полный день  сменный график  \
0              True         False       False         True            True
1              True         False       False         True            True
2             False         False       False         True           False
3              True         False       False        False           False
4             False         False       False         True           False

   гибкий график  удаленная работа  вахтовый метод
0           True              True            True
1           True              True           False
2          False             False           False
3           True              True           False
4          False             False           False

Последние строки:
                                       Пол, возраст           ЗП  \
44739    Мужчина ,  30 лет , родился 17 января 1989   50000 руб.
44740      Мужчина ,  27 лет , родился 5 марта 1992   39000 руб.
44741  Женщина ,  48 лет , родилась 26 декабря 1970   40000 руб.
44742   Мужчина ,  24 года , родился 6 октября 1994   20000 руб.
44743    Мужчина ,  38 лет , родился 25 апреля 1980  120000 руб.

                               Ищет работу на должность:  \
44739  Финансист, аналитик, экономист, бухгалтер, мен...
44740             Системный администратор, IT-специалист
44741                         Аналитик данных, Математик
44742                                   Контент-менеджер
44743                               Руководитель проекта

                            Город, переезд, командировки  \
44739  Тверь , готов к переезду (Москва, Химки) , гот...
44740  Липецк , готов к переезду , готов к командировкам
44741  Челябинск , готова к переезду , готова к редки...
44742  Тамбов , не готов к переезду , не готов к кома...
44743  Москва , не готов к переезду , не готов к кома...

                                             Опыт работы  \
44739  Опыт работы 7 лет 7 месяцев  Финансист, аналит...
44740  Опыт работы 7 лет  Системный администратор, IT...
44741  Опыт работы 21 год 5 месяцев  Январь 1998 — по...
44742  Опыт работы 3 года 10 месяцев  Контент-менедже...
44743  Опыт работы 15 лет 10 месяцев  Руководитель пр...

                         Последнее/нынешнее место работы  \
44739  ООО "IAS" (независимый участник объединения Ru...
44740                                       ИП Пестрецов
44741  ОАО «ЧМК», Исследовательско-Технологический Це...
44742                                          IQ-Maxima
44743                                  ПАО ГК ТНС энерго

                    Последняя/нынешняя должность  \
44739                     Руководитель субгруппы
44740                            Предприниматель
44741                 Начальник группы аналитики
44742                          Менеджер проектов
44743  Руководитель отдела технической поддержки

                                       Образование и ВУЗ Обновление резюме  \
44739  Высшее образование 2015  Московский гуманитарн...  22.04.2019 12:32
44740  Высшее образование (Бакалавр) 2016  Воронежски...  22.04.2019 13:11
44741  Высшее образование 2000  Южно-Уральский госуда...  09.04.2019 05:07
44742  Высшее образование 2015  Тамбовский государств...  26.04.2019 14:25
44743  Высшее образование 1997  Южно-Российский госуд...  05.07.2018 20:15

                                 Авто  полная занятость  частичная занятость  \
44739                      Не указано              True                False
44740                      Не указано              True                 True
44741                      Не указано              True                False
44742  Имеется собственный автомобиль              True                 True
44743                      Не указано              True                False

       проектная работа  волонтерство  стажировка  полный день  \
44739             False         False       False         True
44740              True         False       False         True
44741             False         False       False         True
44742             False         False       False        False
44743             False         False       False         True

       сменный график  гибкий график  удаленная работа  вахтовый метод
44739           False          False              True           False
44740            True           True              True           False
44741           False          False              True           False
44742           False          False              True           False
44743           False          False             False           False

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**.
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата,
* "proportion" - пропорция,
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования:
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [35]:

import pandas as pd
import numpy as np
import zipfile
from io import BytesIO
import requests

# URL файлов с данными
data_url = "https://www.dropbox.com/scl/fi/rcb7dssk2ag0glzkfm1m1/dst-3.0_16_1_hh_database-2.csv?rlkey=tj3ky952fzqc2qp0pmsl827nb&st=q57dz7v6&dl=1"
exchange_rates_url = "https://lms-cdn.skillfactory.ru/assets/courseware/v1/15abf80f45a2f3e93c3274101b451c67/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block/ExchangeRates.zip"

# Загрузка данных
df = pd.read_csv(data_url)

# Загрузка и распаковка архива с курсами валют
response = requests.get(exchange_rates_url)
with zipfile.ZipFile(BytesIO(response.content)) as z:
    z.extractall()

# Загрузка данных о курсах валют
currency_rates = pd.read_csv("ExchangeRates.csv")

# Преобразование даты в датафрейме с курсами валют
currency_rates['date'] = pd.to_datetime(currency_rates['date'], format='%Y-%m-%d')
currency_rates['rate'] = currency_rates['close'] / currency_rates['proportion']


def convert_salary(row, rates_df):
    salary_str = row['ЗП']
    if pd.isna(salary_str):
        return np.nan
    
    parts = salary_str.split()
    amount = float(parts[0])
    currency = parts[1]
    
    if currency == 'руб.':
        return amount

    update_date = pd.to_datetime(row['Обновление резюме'].split()[0], format='%d.%m.%Y')
    rate_row = rates_df[(rates_df['currency'] == currency) & (rates_df['date'] <= update_date)].sort_values(by='date', ascending=False).head(1)
    
    if not rate_row.empty:
        rate = rate_row['rate'].values[0]
        return amount * rate
    else:
        return np.nan


# Преобразование зарплаты в рубли
df['ЗП (руб)'] = df.apply(lambda row: convert_salary(row, currency_rates), axis=1)

# Удаление старого столбца
df = df.drop(columns=['ЗП'])

# Вывод первых строк для проверки
print("Первые строки:")
print(df.head())

# Вывод последних строк для проверки
print("\nПоследние строки:")
print(df.tail())

ParserError: Error tokenizing data. C error: Expected 19 fields in line 3, saw 21

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [5]:
# ваш код здесь
pip install matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# Построение гистограммы
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['Возраст'], bins=30, kde=True)
plt.title('Распределение возраста')
plt.xlabel('Возраст')
plt.ylabel('Частота')

# Построение коробчатой диаграммы
plt.subplot(1, 2, 2)
sns.boxplot(x=df['Возраст'])
plt.title('Коробчатая диаграмма возраста')
plt.xlabel('Возраст')

plt.tight_layout()
plt.show()

# Статистическое описание
age_stats = df['Возраст'].describe()
age_mode = df['Возраст'].mode()[0]

print(age_stats)
print(f"Мода: {age_mode}")

Q1 = df['Возраст'].quantile(0.25)
Q3 = df['Возраст'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Возраст большинства соискателей находится в интервале от {Q1} до {Q3} лет.")
print(f"Значения за пределами {lower_bound} и {upper_bound} можно считать аномальными.")

SyntaxError: invalid syntax (1856188193.py, line 2)

ваши выводы по графику здесь

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [1]:
# ваш код здесь

import matplotlib.pyplot as plt
import seaborn as sns

# Построение гистограммы
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['Опыт работы (месяц)'].dropna(), bins=30, kde=True)
plt.title('Распределение опыта работы (месяц)')
plt.xlabel('Опыт работы (месяц)')
plt.ylabel('Частота')

# Построение коробчатой диаграммы
plt.subplot(1, 2, 2)
sns.boxplot(x=df['Опыт работы (месяц)'].dropna())
plt.title('Коробчатая диаграмма опыта работы (месяц)')
plt.xlabel('Опыт работы (месяц)')

plt.tight_layout()
plt.show()

# Статистическое описание
experience_stats = df['Опыт работы (месяц)'].describe()
experience_mode = df['Опыт работы (месяц)'].mode()[0]

print(experience_stats)
print(f"Мода: {experience_mode}")


Q1 = df['Опыт работы (месяц)'].quantile(0.25)
Q3 = df['Опыт работы (месяц)'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Опыт работы большинства соискателей находится в интервале от {Q1} до {Q3} месяцев.")
print(f"Значения за пределами {lower_bound} и {upper_bound} можно считать аномальными.")

ModuleNotFoundError: No module named 'matplotlib'

ваши выводы здесь

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [3]:
# ваш код здесь

import matplotlib.pyplot as plt
import seaborn as sns

# Построение гистограммы
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['ЗП (руб)'].dropna(), bins=30, kde=True)
plt.title('Распределение заработной платы (руб)')
plt.xlabel('Заработная плата (руб)')
plt.ylabel('Частота')

# Построение коробчатой диаграммы
plt.subplot(1, 2, 2)
sns.boxplot(x=df['ЗП (руб)'].dropna())
plt.title('Коробчатая диаграмма заработной платы (руб)')
plt.xlabel('Заработная плата (руб)')

plt.tight_layout()
plt.show()

# Статистическое описание
salary_stats = df['ЗП (руб)'].describe()
salary_mode = df['ЗП (руб)'].mode()[0]

print(salary_stats)
print(f"Мода: {salary_mode}")

Q1 = df['ЗП (руб)'].quantile(0.25)
Q3 = df['ЗП (руб)'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Заработная плата большинства соискателей находится в интервале от {Q1} до {Q3} рублей.")
print(f"Значения за пределами {lower_bound} и {upper_bound} можно считать аномальными.")

ModuleNotFoundError: No module named 'matplotlib'

ваши выводы здесь

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [6]:
# ваш код здесь

import pandas as pd
import matplotlib.pyplot as plt

# Фильтрация данных
filtered_df = df[df['ЗП (руб)'] < 1_000_000]

# Вычисление медианной ЗП по уровням образования
median_salary_by_education = filtered_df.groupby('Образование')['ЗП (руб)'].median().reset_index()

# Построение диаграммы
plt.figure(figsize=(10, 6))
plt.bar(median_salary_by_education['Образование'], median_salary_by_education['ЗП (руб)'], color='skyblue')
plt.xlabel('Уровень образования')
plt.ylabel('Медианная заработная плата (руб)')
plt.title('Медианная заработная плата по уровням образования')
plt.xticks(rotation=45)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

ваши выводы здесь

Наибольшие уровни желаемой заработной платы наблюдаются у соискателей с высшим образованием, особенно с учеными степенями (кандидат или доктор наук).
Наименьшие уровни желаемой заработной платы наблюдаются у соискателей со средним образованием и ниже.
Важность признака уровня образования: Уровень образования является значимым признаком при прогнозировании заработной платы, так как существует четкая зависимость между уровнем образования и медианной заработной платой, где более высокий уровень образования связан с более высокими уровнями желаемой заработной платы.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [7]:
# ваш код здесь

import seaborn as sns

# Фильтрация данных
filtered_df = df[df['ЗП (руб)'] < 1_000_000]

# Построение диаграммы
plt.figure(figsize=(12, 6))
sns.boxplot(data=filtered_df, x='Город', y='ЗП (руб)', palette='Set2')
plt.xlabel('Город')
plt.ylabel('Желаемая заработная плата (руб)')
plt.title('Распределение желаемой заработной платы по городам')
plt.xticks(rotation=45)
plt.show()

ModuleNotFoundError: No module named 'seaborn'

ваши выводы здесь

Медианные уровни желаемой заработной платы: В крупных городах, таких как Москва и Санкт-Петербург, медианные уровни заработной платы выше, чем в городах-миллионниках и других городах.
Размах значений: В Москве и Санкт-Петербурге также наблюдается больший размах значений, что может указывать на более широкий диапазон желаемых заработных плат среди соискателей.
Важность признака города: Признак города является значимым при прогнозировании заработной платы, так как уровень и размах желаемой заработной платы заметно различаются в зависимости от города, что может быть связано с различными уровнями жизни и стоимости труда в разных регионах.

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [8]:
# ваш код здесь

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Фильтрация данных
filtered_df = df[df['ЗП (руб)'] < 1_000_000]

# Группировка данных и вычисление медианной заработной платы
median_salary = filtered_df.groupby(['Готовность к переезду', 'Готовность к командировкам'])['ЗП (руб)'].median().reset_index()

# Построение многоуровневой столбчатой диаграммы
plt.figure(figsize=(12, 6))
sns.barplot(data=median_salary, x='Готовность к переезду', y='ЗП (руб)', hue='Готовность к командировкам', palette='Set2')
plt.xlabel('Готовность к переезду')
plt.ylabel('Медианная заработная плата (руб)')
plt.title('Медианная заработная плата по готовности к переезду и командировкам')
plt.show()

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
ваши выводы здесь

отовность к переезду и командировкам: Соискатели, готовые к переезду и командировкам, в среднем запрашивают более высокую заработную плату.
Влияние командировок: Готовность к командировкам, в сочетании с готовностью к переезду, также показывает более высокие медианные значения заработной платы.
Отсутствие готовности: Соискатели, не готовые ни к переезду, ни к командировкам, имеют самые низкие медианные значения заработной платы.
Значимость признаков: Признаки готовности к переезду и командировкам оказывают значительное влияние на желаемую заработную плату, и их следует учитывать при прогнозировании зарплатных ожиданий.

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [9]:
# ваш код здесь

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Создание сводной таблицы
pivot_table = df.pivot_table(
    values='ЗП (руб)', 
    index='Возраст', 
    columns='Образование', 
    aggfunc='median'
)

# Построение тепловой карты
plt.figure(figsize=(12, 8))
sns.heatmap(pivot_table, annot=True, fmt=".0f", cmap="YlGnBu")
plt.title('Тепловая карта медианной заработной платы по возрасту и образованию')
plt.xlabel('Образование')
plt.ylabel('Возраст')
plt.show()

ModuleNotFoundError: No module named 'seaborn'

ваши выводы здесь

Возрастные группы: Заработная плата увеличивается с возрастом, достигая пика в определенные возрастные группы, а затем может снижаться.
Уровень образования: Соискатели с высшим образованием имеют более высокие медианные заработные платы по всем возрастным группам.
Взаимосвязь возраста и образования: Высшее образование имеет значительное влияние на желаемую заработную плату, особенно в сочетании с увеличением возраста и опыта работы.
Аномалии и пики: Можно заметить некоторые аномалии и пики в определенных возрастных группах, что может указывать на влияние других факторов, таких как профессия или сфера деятельности.

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [10]:
# ваш код здесь

import pandas as pd
import matplotlib.pyplot as plt

# Преобразование опыта работы из месяцев в года
df['Опыт работы (год)'] = df['Опыт работы (месяц)'] / 12

# Построение диаграммы рассеяния
plt.figure(figsize=(10, 6))
plt.scatter(df['Возраст'], df['Опыт работы (год)'], alpha=0.5)

# Построение прямой (0, 0) - (100, 100)
plt.plot([0, 100], [0, 100], color='red', linewidth=2)

plt.xlabel('Возраст')
plt.ylabel('Опыт работы (годы)')
plt.title('Зависимость опыта работы от возраста')
plt.grid(True)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

ваши выводы здесь

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
# ваш код здесь

ваши выводы здесь

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [11]:
# ваш код здесь

import pandas as pd

# Загрузка данных
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Проверка на наличие полных дубликатов
duplicates = df.duplicated(keep=False)
print("Количество полных дубликатов: ", duplicates.sum())

# Удаление полных дубликатов
df_cleaned = df.drop_duplicates()

# Проверка, что дубликаты удалены
print("Количество строк после удаления дубликатов: ", df_cleaned.shape[0])

# Сохранение очищенного DataFrame
df_cleaned.to_csv('cleaned_resume_data.csv', index=False)

Количество полных дубликатов:  306
Количество строк после удаления дубликатов:  44591

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [13]:
# ваш код здесь

import pandas as pd

# Загрузка данных
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Вывод информации о числе пропусков в столбцах
missing_values = df.isnull().sum()
print(missing_values)

Пол, возраст                         0
ЗП                                   0
Ищет работу на должность:            0
Город, переезд, командировки         0
Занятость                            0
График                               0
Опыт работы                        168
Последнее/нынешнее место работы      1
Последняя/нынешняя должность         2
Образование и ВУЗ                    0
Обновление резюме                    0
Авто                                 0
dtype: int64

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [14]:
# ваш код здесь

import pandas as pd

# Загрузка данных
df = pd.read_csv("C:/Users/user/Downloads/dst-3.0_16_1_hh_database.csv", sep=";")

# Удаление строк с пропусками в столбцах "Последнее/нынешнее место работы" и "Последняя/нынешняя должность"
df.dropna(subset=['Последнее/нынешнее место работы', 'Последняя/нынешняя должность'], inplace=True)

# Заполнение пропусков в столбце "Опыт работы (месяц)" медианным значением
median_experience = df['Опыт работы (месяц)'].median()
df['Опыт работы (месяц)'].fillna(median_experience, inplace=True)

# Проверка результатов
print(df.isnull().sum())

KeyError: 'Опыт работы (месяц)'

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [15]:
# ваш код здесь

# Фильтрация данных по диапазону заработной платы
df = df[(df['ЗП (руб)'] >= 1000) & (df['ЗП (руб)'] <= 1000000)]

# Проверка результатов
print(f"Число оставшихся резюме: {len(df)}")

KeyError: 'ЗП (руб)'

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [16]:
# ваш код здесь

# Добавляем столбец "Опыт работы (годы)" для удобства
df['Опыт работы (годы)'] = df['Опыт работы (месяц)'] / 12

# Находим резюме, где опыт работы превышает возраст
invalid_experience = df[df['Опыт работы (годы)'] > df['Возраст']]

# Удаляем эти резюме
df = df.drop(invalid_experience.index)

# Проверка результатов
print(f"Число оставшихся резюме: {len(df)}")

KeyError: 'Опыт работы (месяц)'

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [17]:
# ваш код здесь

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Логарифмирование возраста
log_age = np.log(df['Возраст'])

# Построение гистограммы
plt.figure(figsize=(10, 6))
histplot = sns.histplot(log_age, kde=True, bins=30)
histplot.axvline(log_age.mean(), color='k', lw=2)
histplot.axvline(log_age.mean() + 3 * log_age.std(), color='r', linestyle='--', lw=2)
histplot.axvline(log_age.mean() - 3 * log_age.std(), color='r', linestyle='--', lw=2)
histplot.axvline(log_age.mean() + 4 * log_age.std(), color='g', linestyle='--', lw=2)

plt.title('Распределение возраста в логарифмическом масштабе')
plt.xlabel('Логарифм возраста')
plt.ylabel('Частота')
plt.show()

# Оценка выбросов методом z-отклонения
z_scores = (log_age - log_age.mean()) / log_age.std()
outliers = df[(z_scores > 4)]

# Удаление выбросов
df = df[(z_scores <= 4)]

# Вывод информации о выбросах
print("Выбросы:")
print(outliers)

ModuleNotFoundError: No module named 'matplotlib'

ваш коммментарий здесь